services:
  client:
    build:
      context: ../client
      args:
        ENVIRONMENT: development
    restart: always
    ports:
      - '8080:80'
  server:
    build: ../server
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/word-trainer
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: word-trainer
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: word-trainer
      ME_CONFIG_MONGO_DB_SERVER: mongo

volumes:
  mongodb_data:
    driver: local
