export const SECOND_IN_MILLISECONDS = 1000;
export const MINUTE_IN_MILLISECONDS = 60000;
export const HOUR_IN_MILLISECONDS = 3600000;
export const DAY_IN_MILLISECONDS = 86400000;
export const WEEK_IN_MILLISECONDS = DAY_IN_MILLISECONDS * 7;
export const MONTH_IN_MILLISECONDS = DAY_IN_MILLISECONDS * 30;
export const YEAR_IN_MILLISECONDS = DAY_IN_MILLISECONDS * 365;
