name: Check changes in client folder

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

defaults:
  run:
    shell: bash
    working-directory: ./client


jobs:
  test-client-folder:
    name: 'Test client folder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - name: 'Install Dependencies'
        run: yarn install

      - name: 'Generate Types'
        run: yarn codegen

      - name: 'Run Tests'
        run: yarn test

      - name: 'Run Type Check'
        run: yarn type-check

      - name: 'Run Lint Check'
        run: yarn lint-check
