name: Test server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

defaults:
  run:
    shell: bash
    working-directory: ./server

jobs:
  test-server-folder:
    name: 'Test server folder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Use Node.js 18.x'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: 'Cache node_modules'
        uses: actions/cache@v4
        with:
          path: ./server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: 'Run Tests'
        run: yarn test

      - name: 'Run Type Check'
        run: yarn type-check

      - name: 'Run Lint Check'
        run: yarn lint-check
